services:

  app:
    build: .
    container_name: portfolio_app
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - uploads_data:/var/www/html/assets/uploads
    environment:
      - BD_HOST=${BD_HOST}
      - BD_USUARIO=${BD_USUARIO}
      - BD_CONTRASENA=${BD_CONTRASENA}
      - BD_NOMBRE=${BD_NOMBRE}
    networks:
      - portfolio_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: portfolio_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${BD_HOST}
      PMA_PORT: 3306
      PMA_USER: ${BD_USUARIO}
      PMA_PASSWORD: ${BD_CONTRASENA}
    networks:
      - portfolio_net

volumes:
  uploads_data:

networks:
  portfolio_net:
    driver: bridge